# =============================================================================
# ECR Image Pull Secret for Test Runner
# =============================================================================
# Uses centralized ClusterECRAuthorizationToken from external-secrets namespace.
# The kubestock-external-secrets IAM user generates ECR tokens centrally.
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-cred
  namespace: test-runner
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ecr-cred
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          expiresAt: "{{ .expires_at }}"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint | replace "https://" "" }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterECRAuthorizationToken
          name: ecr-token-generator
