# =============================================================================
# ArgoCD Project - Infrastructure Components
# =============================================================================
# Project for cluster-wide infrastructure components like:
# - CSI Drivers (EBS, EFS)
# - Cert-Manager
# - External-Secrets Operator
# - Observability Stack
# - Cluster Autoscaler
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubestock-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: KubeStock Infrastructure Components - Cluster-wide services

  # Source repositories allowed
  sourceRepos:
    - 'https://github.com/KubeStock-DevOps-project/kubestock-gitops.git'

  # Destination clusters and namespaces
  destinations:
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
    - namespace: 'observability'
      server: https://kubernetes.default.svc
    - namespace: 'external-secrets'
      server: https://kubernetes.default.svc
    - namespace: 'cert-manager'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
    - namespace: 'test-runner'
      server: https://kubernetes.default.svc
    - namespace: 'cluster-autoscaler'
      server: https://kubernetes.default.svc

  # Cluster-scoped resources allowed (infrastructure needs more permissions)
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'storage.k8s.io'
      kind: StorageClass
    - group: 'storage.k8s.io'
      kind: CSIDriver
    - group: 'storage.k8s.io'
      kind: CSINode
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'scheduling.k8s.io'
      kind: PriorityClass
    - group: 'apiregistration.k8s.io'
      kind: APIService

  # Namespace-scoped resources allowed
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: ReplicaSet
    - group: 'apps'
      kind: DaemonSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'external-secrets.io'
      kind: ExternalSecret
    - group: 'generators.external-secrets.io'
      kind: ECRAuthorizationToken

  # Allow sync anytime for infrastructure
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - '*'

  # Roles for RBAC
  roles:
    - name: infra-admin
      description: Full access to infrastructure project
      policies:
        - p, proj:kubestock-infrastructure:infra-admin, applications, *, kubestock-infrastructure/*, allow
      groups:
        - admin
