---
# ArgoCD Project - Production Environment
# Uses rolling update deployment strategy
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubestock-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: KubeStock Production Environment

  # Source repositories allowed (restricted to org repos only)
  sourceRepos:
    - 'https://github.com/KubeStock-DevOps-project/kubestock-gitops.git'

  # Destination clusters and namespaces
  destinations:
    # Production namespace for live traffic
    - namespace: 'kubestock-production'
      server: https://kubernetes.default.svc
    # Kong gateway namespace for production
    - namespace: 'kong'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
    # Observability namespace (Prometheus, Grafana, Alertmanager)
    - namespace: 'observability-production'
      server: https://kubernetes.default.svc

  # Cluster-scoped resources allowed
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'storage.k8s.io'
      kind: StorageClass
    - group: 'external-secrets.io'
      kind: ClusterSecretStore
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding

  # Namespace-scoped resources allowed
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: ReplicaSet
    - group: 'apps'
      kind: DaemonSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'external-secrets.io'
      kind: ExternalSecret
    - group: 'generators.external-secrets.io'
      kind: ECRAuthorizationToken
    - group: 'security.istio.io'
      kind: PeerAuthentication
    - group: 'security.istio.io'
      kind: AuthorizationPolicy
    - group: 'security.istio.io'
      kind: RequestAuthentication

  # Orphaned resources warning (don't auto-delete)
  # Ignore secrets that are managed externally
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        name: aws-external-secrets-creds
      - group: ""
        kind: Secret
        name: ecr-cred

  # Roles for RBAC
  roles:
    - name: production-admin
      description: Full access to production project (requires approval)
      policies:
        - p, proj:kubestock-production:production-admin, applications, *, kubestock-production/*, allow
      groups:
        - admin

    - name: production-deployer
      description: Can sync but not delete production apps
      policies:
        - p, proj:kubestock-production:production-deployer, applications, get, kubestock-production/*, allow
        - p, proj:kubestock-production:production-deployer, applications, sync, kubestock-production/*, allow
      groups:
        - deployer

    - name: production-viewer
      description: Read-only access to production
      policies:
        - p, proj:kubestock-production:production-viewer, applications, get, kubestock-production/*, allow
      groups:
        - viewer
        - developer