# Authorization policies for API endpoints
# Require valid JWT for protected services (applied at workload sidecar level)
# NOTE: Using DENY policy with notRequestPrincipals to reject unauthenticated requests
---
# Deny requests without valid JWT for API microservices
# This DENY policy ensures requests without valid JWT are rejected
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-without-jwt-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: DENY
  rules:
    # Deny requests without valid JWT (notRequestPrincipals means no valid principal)
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            # Deny all methods except OPTIONS (CORS preflight) and health checks
            notMethods: ["OPTIONS"]
            notPaths: ["/health", "/health/*", "/metrics"]
---
# Deny requests without valid JWT for API microservices in production
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-without-jwt-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: DENY
  rules:
    # Deny requests without valid JWT
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notMethods: ["OPTIONS"]
            notPaths: ["/health", "/health/*", "/metrics"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
