# =============================================================================
# Authorization Policies for KubeStock Services
# =============================================================================
# JWT validation happens at sidecar level via RequestAuthentication.
# These DENY policies reject requests without valid JWT for protected services.
# =============================================================================
---
# Deny requests without valid JWT - Staging
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-without-jwt-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notMethods: ["OPTIONS"]
            notPaths: ["/health", "/health/*", "/metrics"]
---
# Deny requests without valid JWT - Production
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-without-jwt-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notMethods: ["OPTIONS"]
            notPaths: ["/health", "/health/*", "/metrics"]
---
# Allow all traffic to Identity Service (handles its own auth for SCIM2)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
# Allow all traffic to Frontend (static files, no auth needed)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
# =============================================================================
# ALLOW policies for microservices
# =============================================================================
# These policies allow traffic that passes the DENY checks above.
# Without these, requests would be implicitly denied because other ALLOW 
# policies exist in the namespace (for frontend and identity).
# =============================================================================
---
# Allow traffic to services with require-jwt label (after DENY check passes)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-jwt-services-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-jwt-services-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: ALLOW
  rules:
    - {}
