# Authorization policies for API endpoints
# Require valid JWT for protected services (applied at workload sidecar level)
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-staging
  namespace: kubestock-staging
spec:
  action: ALLOW
  rules:
    # Allow valid JWT holders
    - from:
        - source:
            requestPrincipals: ["*"]
    # Allow CORS preflight
    - to:
        - operation:
            methods: ["OPTIONS"]
    # Allow health checks from anywhere (GET /health)
    - from:
        - source:
            namespaces: ["istio-system"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/health", "/health/*"]
    # Also allow health checks without source restriction (for testing)
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/health"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-production
  namespace: kubestock-production
spec:
  action: ALLOW
  rules:
    # Allow valid JWT holders
    - from:
        - source:
            requestPrincipals: ["*"]
    # Allow CORS preflight
    - to:
        - operation:
            methods: ["OPTIONS"]
    # Allow health checks from ingress gateway
    - from:
        - source:
            namespaces: ["istio-system"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/health", "/health/*"]
    # Also allow health checks without source restriction
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/health"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
