# Authorization policies for API endpoints
# Require valid JWT for protected services (applied at workload sidecar level)
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-staging
  namespace: kubestock-staging
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            methods: ["OPTIONS"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-production
  namespace: kubestock-production
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            methods: ["OPTIONS"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
