# Authorization policies for API endpoints
# Require valid JWT for protected services (applied at workload sidecar level)
---
# JWT Authorization for API microservices only
# Frontend and Identity services have their own allow-all policies
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-staging
  namespace: kubestock-staging
spec:
  # Apply only to ms-product
  selector:
    matchLabels:
      require-jwt: "true"
  action: ALLOW
  rules:
    # Allow valid JWT holders
    - from:
        - source:
            requestPrincipals: ["*"]
    # Allow CORS preflight
    - to:
        - operation:
            methods: ["OPTIONS"]
    # Allow health checks
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/health", "/health/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  action: ALLOW
  rules:
    # Allow valid JWT holders
    - from:
        - source:
            requestPrincipals: ["*"]
    # Allow CORS preflight
    - to:
        - operation:
            methods: ["OPTIONS"]
    # Allow health checks
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/health", "/health/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-identity-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-staging
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontend-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: frontend
  action: ALLOW
  rules:
    - {}
