# Gateway configuration for Istio ingress
# TLS termination happens at AWS ALB, so gateway only needs HTTP
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kubestock-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
