# Mesh-wide STRICT mTLS
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-mtls
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
# Allow Prometheus to scrape metrics from staging services
# PERMISSIVE mode on metrics ports allows both mTLS and plaintext
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-metrics-scraping
  namespace: kubestock-staging
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  mtls:
    mode: STRICT
  portLevelMtls:
    # ms-product
    3002:
      mode: PERMISSIVE
    # ms-inventory
    3003:
      mode: PERMISSIVE
    # ms-supplier
    3004:
      mode: PERMISSIVE
    # ms-order-management
    3005:
      mode: PERMISSIVE
    # ms-identity
    3006:
      mode: PERMISSIVE
---
# Allow Prometheus to scrape metrics from production services
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-metrics-scraping
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  mtls:
    mode: STRICT
  portLevelMtls:
    # ms-product
    3002:
      mode: PERMISSIVE
    # ms-inventory
    3003:
      mode: PERMISSIVE
    # ms-supplier
    3004:
      mode: PERMISSIVE
    # ms-order-management
    3005:
      mode: PERMISSIVE
    # ms-identity
    3006:
      mode: PERMISSIVE
