# =============================================================================
# JWT validation at sidecar level
# =============================================================================
# Validates JWT signature using Asgardeo's JWKS endpoint
# Also validates issuer and audience claims
# Forwards original token to services for application-level authorization
# =============================================================================
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth-staging
  namespace: kubestock-staging
spec:
  # Apply to workloads that require JWT
  selector:
    matchLabels:
      require-jwt: "true"
  jwtRules:
    - issuer: "https://api.asgardeo.io/t/kubestock/oauth2/token"
      # JWKS endpoint for signature verification
      jwksUri: "https://api.asgardeo.io/t/kubestock/oauth2/jwks"
      audiences:
        - "NydMISKZZ5TdIEuRwJfYv62Yn7ka"  # SPA Application
        - "6e6DeVI9oNaoYV6SSi7cWjIckMQa"  # Test Runner Application
      forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth-production
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  jwtRules:
    - issuer: "https://api.asgardeo.io/t/kubestock/oauth2/token"
      jwksUri: "https://api.asgardeo.io/t/kubestock/oauth2/jwks"
      audiences:
        - "NydMISKZZ5TdIEuRwJfYv62Yn7ka"  # SPA Application
        - "6e6DeVI9oNaoYV6SSi7cWjIckMQa"  # Test Runner Application
      forwardOriginalToken: true
