# =============================================================================
# Staging VirtualService - Routes to kubestock-staging namespace
# =============================================================================
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubestock-routes-staging
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - kubestock-gateway-staging  # Staging gateway
  http:
    # Health endpoint for NLB
    - match:
        - uri:
            exact: /api/gateway/health
      directResponse:
        status: 200
        body:
          string: '{"status":"healthy","gateway":"istio","environment":"staging"}'

    # Product Service
    # /api/product -> /, /api/product/ -> /, /api/product/categories -> /categories
    - match:
        - uri:
            prefix: /api/product
      rewrite:
        uri: /
      route:
        - destination:
            host: ms-product.kubestock-staging.svc.cluster.local
            port:
              number: 3002
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - X-Request-ID
        allowCredentials: true
        maxAge: "3600s"

    # Inventory Service
    - match:
        - uri:
            prefix: /api/inventory
      rewrite:
        uri: /
      route:
        - destination:
            host: ms-inventory.kubestock-staging.svc.cluster.local
            port:
              number: 3003
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - X-Request-ID
        allowCredentials: true
        maxAge: "3600s"

    # Supplier Service
    - match:
        - uri:
            prefix: /api/supplier
      rewrite:
        uri: /
      route:
        - destination:
            host: ms-supplier.kubestock-staging.svc.cluster.local
            port:
              number: 3004
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - X-Request-ID
        allowCredentials: true
        maxAge: "3600s"

    # Order Management Service
    - match:
        - uri:
            prefix: /api/order
      rewrite:
        uri: /
      route:
        - destination:
            host: ms-order-management.kubestock-staging.svc.cluster.local
            port:
              number: 3005
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - X-Request-ID
        allowCredentials: true
        maxAge: "3600s"

    # Identity Service
    - match:
        - uri:
            prefix: /api/identity
      rewrite:
        uri: /
      route:
        - destination:
            host: ms-identity.kubestock-staging.svc.cluster.local
            port:
              number: 3006
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - X-Request-ID
        allowCredentials: true
        maxAge: "3600s"

    # Frontend (catch-all)
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.kubestock-staging.svc.cluster.local
            port:
              number: 80
