# =============================================================================
# Loki - PersistentVolumeClaim
# =============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
