# =============================================================================
# Kong ClusterRoleBinding for Production
# =============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-ingress-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kong-ingress
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong
