---
# Staging Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kubestock-staging
  labels:
    environment: staging
    app.kubernetes.io/part-of: kubestock
    argocd.argoproj.io/managed-by: argocd
    istio-injection: enabled
---
# Resource Quota for Staging (cost control)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: kubestock-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    requests.storage: 50Gi
---
# Limit Range for Staging
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: kubestock-staging
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
