# =============================================================================
# PeerAuthentication - Allow Prometheus to scrape metrics
# =============================================================================
# PERMISSIVE mode on application ports allows non-mesh Prometheus
# to scrape metrics while keeping STRICT mTLS for service-to-service traffic
# =============================================================================
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-metrics-scraping
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      require-jwt: "true"
  mtls:
    mode: STRICT
  portLevelMtls:
    # ms-product
    "3002":
      mode: PERMISSIVE
    # ms-inventory
    "3003":
      mode: PERMISSIVE
    # ms-supplier
    "3004":
      mode: PERMISSIVE
    # ms-order-management
    "3005":
      mode: PERMISSIVE
    # ms-identity
    "3006":
      mode: PERMISSIVE
---
# Allow Prometheus to scrape ms-identity (doesn't have require-jwt label)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-metrics-identity
  namespace: kubestock-production
spec:
  selector:
    matchLabels:
      app: ms-identity
  mtls:
    mode: STRICT
  portLevelMtls:
    "3006":
      mode: PERMISSIVE
