apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-external-secrets-creds
            key: access-key-id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-external-secrets-creds
            key: secret-access-key
            namespace: external-secrets
