# =============================================================================
# RBAC for ECR Token Distribution
# =============================================================================
# Allows External Secrets controller to push ECR tokens to application namespaces.
#
# Security Model:
# - AWS credentials exist ONLY in external-secrets namespace
# - ECR token generated centrally, pushed to app namespaces
# - Only generated ECR tokens (expire in 12h) exist in app namespaces
# - No AWS credential replication across namespaces
# =============================================================================

# Role in staging namespace to allow secret creation
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-ecr-pusher
  namespace: kubestock-staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-ecr-pusher
  namespace: kubestock-staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-ecr-pusher
  apiGroup: rbac.authorization.k8s.io
---
# Role in production namespace to allow secret creation
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-ecr-pusher
  namespace: kubestock-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-ecr-pusher
  namespace: kubestock-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-ecr-pusher
  apiGroup: rbac.authorization.k8s.io
---
# Role in test-runner namespace to allow secret creation
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-ecr-pusher
  namespace: test-runner
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-ecr-pusher
  namespace: test-runner
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-ecr-pusher
  apiGroup: rbac.authorization.k8s.io
