# =============================================================================
# ExternalSecret for Test Runner - Staging
# =============================================================================
# Fetches test runner credentials from AWS Secrets Manager
# Secret path: kubestock/shared/test-runner (shared across environments)
# Token URL from: kubestock/staging/asgardeo
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-runner-secret
  namespace: kubestock-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: test-runner-secret
    creationPolicy: Owner
  data:
    # Test Runner OAuth Client Credentials (from shared secret)
    - secretKey: ASGARDEO_TEST_CLIENT_ID
      remoteRef:
        key: kubestock/shared/test-runner
        property: client_id
    - secretKey: ASGARDEO_TEST_CLIENT_SECRET
      remoteRef:
        key: kubestock/shared/test-runner
        property: client_secret
    # Test User Credentials (from shared secret)
    - secretKey: ASGARDEO_USERNAME
      remoteRef:
        key: kubestock/shared/test-runner
        property: username
    - secretKey: ASGARDEO_PASSWORD
      remoteRef:
        key: kubestock/shared/test-runner
        property: password
    # Token URL from staging asgardeo config
    - secretKey: ASGARDEO_TOKEN_URL
      remoteRef:
        key: kubestock/staging/asgardeo
        property: ASGARDEO_TOKEN_URL
