# =============================================================================
# Stakater Reloader - ServiceAccount
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reloader
  namespace: reloader
  labels:
    app.kubernetes.io/name: reloader
