# =============================================================================
# Kong API Gateway RBAC - Base (Shared ClusterRole only)
# =============================================================================
# NOTE: ClusterRoleBinding is environment-specific and defined in overlays
# =============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-ingress
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins", "kongconsumers", "kongcredentials", "kongingresses"]
    verbs: ["get", "list", "watch"]
