apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-production
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: overlays/production/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
