# =============================================================================
# ArgoCD Application - Kubestock Production
# =============================================================================
# Deploys all production services using rolling update strategy
# Auto-sync enabled for GitOps best practices
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubestock-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-production
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: kubestock-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
