# =============================================================================
# ArgoCD Application - Observability Stack (Production)
# =============================================================================
# Completely isolated production observability environment
# - Namespace: observability-production
# - NodePorts: 30090 (Prometheus), 30300 (Grafana), 30093 (Alertmanager)
# - Includes Alertmanager for production alerts
# - Own RBAC, PVCs, and configurations
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-production
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: overlays/production/observability-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: production-prometheus-config
      jsonPointers:
        - /data
