# =============================================================================
# Metrics Server - APIService
# =============================================================================
# Registers metrics-server with the Kubernetes API aggregation layer
# Makes metrics.k8s.io/v1beta1 available cluster-wide
# =============================================================================
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: metrics-server
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  # Skip TLS verification - metrics-server uses self-signed cert
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
