# =============================================================================
# Metrics Server - ServiceAccount
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app: metrics-server
