# =============================================================================
# AWS EBS Storage Class for Dynamic Volume Provisioning
# =============================================================================
# This StorageClass enables automatic provisioning of AWS EBS volumes
# for PersistentVolumeClaims in the cluster
# =============================================================================
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3  # General Purpose SSD (gp3 is cheaper than gp2)
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain  # Keep data even if PVC is deleted
