# =============================================================================
# ArgoCD Application - Test Runner (Staging)
# =============================================================================
# Deploys test-runner service to kubestock-staging namespace
# Manages automated testing infrastructure
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-runner-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-staging
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: overlays/staging/test-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: kubestock-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  ignoreDifferences:
    # Ignore differences in Job status and metadata
    - group: batch
      kind: Job
      jsonPointers:
        - /status
        - /metadata/labels
        - /metadata/annotations
