# =============================================================================
# Promtail - ServiceAccount (Namespaced)
# =============================================================================
# Note: ClusterRole and ClusterRoleBinding are in cluster-resources/
# to avoid conflicts between staging and production ArgoCD apps.
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: observability
  labels:
    app: promtail
