# =============================================================================
# ArgoCD Application - External Secrets Operator
# =============================================================================
# Deploys External Secrets resources (ClusterSecretStore, etc.)
# Note: The operator itself is installed via Helm
# This manages the ExternalSecret CRDs and configurations
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-staging
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: base/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
