# =============================================================================
# ArgoCD Application - External Secrets Prerequisites (Namespace + Credentials)
# =============================================================================
# Deploys the namespace and AWS credentials BEFORE the operator starts.
# This ensures the credentials exist when the operator tries to use them.
#
# Sync Wave: -2 (after operator at -3, but before config at -1)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: base/external-secrets-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
