# =============================================================================
# ArgoCD Application - External Secrets Operator (Helm)
# =============================================================================
# Deploys the External Secrets Operator using the official Helm chart.
# This replaces the previous rendered.yaml approach with proper Helm management.
#
# Deployment Order:
# 1. This app deploys the operator and CRDs
# 2. external-secrets-prereqs deploys the AWS credentials secret
# 3. external-secrets-config deploys ClusterSecretStore, ECR generators, etc.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.19
    helm:
      releaseName: external-secrets
      valueFiles: []
      values: |
        # Install CRDs with the chart
        installCRDs: true
        
        # Replicas
        replicaCount: 1
        
        # Resource limits
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        
        # Webhook configuration
        webhook:
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        
        # Cert controller configuration
        certController:
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        
        # Service account
        serviceAccount:
          create: true
          name: external-secrets
        
        # Metrics for Prometheus
        metrics:
          service:
            enabled: true
            port: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  ignoreDifferences:
    # Ignore webhook CA bundle as it's auto-generated
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
