# =============================================================================
# ArgoCD Application - Kong API Gateway
# =============================================================================
# Deploys Kong gateway in kong namespace
# Auto-sync enabled for GitOps best practices
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-staging  # Kong serves both staging and prod
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: main
    path: base/kong
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
