# =============================================================================
# ArgoCD Application - Stakater Reloader
# =============================================================================
# Automatically restarts workloads when ConfigMaps/Secrets change
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kubestock-infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubestock-infrastructure
  source:
    repoURL: https://github.com/KubeStock-DevOps-project/kubestock-gitops.git
    targetRevision: demo
    path: base/reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
