# =============================================================================
# Promtail RBAC - ClusterRole and ClusterRoleBinding
# =============================================================================
# Note: ClusterRole names are prefixed by overlay using namePrefix
# to create environment-specific roles:
# - promtail-staging
# - promtail-production
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  labels:
    app: promtail

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
  labels:
    app: promtail
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    # Namespace will be set by kustomize
roleRef:
  kind: ClusterRole
  name: promtail
  apiGroup: rbac.authorization.k8s.io
